<?php

CONST COMPANY_USER_STATUS_ACTIVE_ADMIN_ADD= 'ADMIN_ADD';
CONST COMPANY_USER_STATUS_ACTIVE_ADMIN_INVITATION= 'ADMIN_INVITATION';
CONST COMPANY_USER_STATUS_ACTIVE_OWNER_INVITATION= 'OWNER_INVITATION';
CONST COMPANY_USER_STATUS_ACTIVE_USER_REQUEST= 'USER_REQUEST';

CONST COMPANY_USER_STATUS_INACTIVE_ADMIN_REMOVE= 'ADMIN_REMOVE';
CONST COMPANY_USER_STATUS_INACTIVE_OWNER_REMOVE= 'OWNER_REMOVE';
CONST COMPANY_USER_STATUS_INACTIVE_USER_LEAVE= 'USER_LEAVE';