<?php

CONST COMPANY_USER_STATUS_ACTIVE_ADMIN= 'ADMIN';
CONST COMPANY_USER_STATUS_ACTIVE_INVITATION= 'INVITATION';
CONST COMPANY_USER_STATUS_ACTIVE_REQUEST= 'REQUEST';

CONST COMPANY_USER_STATUS_INACTIVE_ADMIN= 'ADMIN';
CONST COMPANY_USER_STATUS_INACTIVE_REMOVE= 'REMOVE';
CONST COMPANY_USER_STATUS_INACTIVE_LEAVE= 'LEAVE';