<?php

CONST ID_USERGROUP_SUPERADMIN= 1;
CONST ID_USERGROUP_ADMIN= 2;
CONST ID_USERGROUP_GUEST= 3;
CONST ID_USERGROUP_REGISTERED= 4;

CONST ID_USER_SUPERADMIN= 1;
CONST ID_USER_SYSTEM= -1;
CONST ID_USER_GUEST= -2;
